/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio3;

import static ejercicio3.Fabricantes.r;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author albert
 */
public class Articulos extends javax.swing.JFrame {

    static public ResultSet r;
    /**
     * Creates new form Articulos
     */
    public Articulos() throws SQLException {
        initComponents();
        guardar.setVisible(false);
        cancelar.setVisible(false);
        String url = "jdbc:mysql://localhost:3306/entornos";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url,user,pass);
        
        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from articulos";
        r = s.executeQuery(query);
        r.first();
        cod_art.setText(r.getString("cod_articulo"));
        arti.setText(r.getString("articulo"));
        fabri.setText(r.getString("fabricante"));
        peso.setText(r.getString("peso"));
        preciovent.setText(r.getString("precio_venta"));
        preciocost.setText(r.getString("precio_coste"));
        existenc.setText(r.getString("existencias"));
        category.setText(r.getString("categoria"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cod_art = new javax.swing.JTextField();
        arti = new javax.swing.JTextField();
        fabri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        preciovent = new javax.swing.JTextField();
        preciocost = new javax.swing.JTextField();
        existenc = new javax.swing.JTextField();
        first = new javax.swing.JButton();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        last = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cod_Articulo");

        jLabel2.setText("Articulo");

        jLabel3.setText("Fabricante");

        cod_art.setEditable(false);

        jLabel4.setText("Peso");

        jLabel5.setText("Categoria");

        jLabel6.setText("Precio_venta");

        jLabel7.setText("Precio_coste");

        jLabel8.setText("Existencias");

        first.setText("Primero");
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });

        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setText("Anterior");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        last.setText("Ultimo");
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });

        edit.setText("Editar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        insert.setText("Insertar");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(first))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(existenc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preciocost, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preciovent, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cod_art, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arti, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fabri, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelar)
                                    .addComponent(guardar))
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(next)
                        .addGap(18, 18, 18)
                        .addComponent(previous)
                        .addGap(18, 18, 18)
                        .addComponent(last)
                        .addGap(18, 18, 18)
                        .addComponent(edit)
                        .addGap(26, 26, 26)
                        .addComponent(insert)))
                .addGap(18, 18, 18)
                .addComponent(volver)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cod_art, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(arti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(guardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preciovent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(preciocost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(existenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first)
                    .addComponent(next)
                    .addComponent(previous)
                    .addComponent(last)
                    .addComponent(edit)
                    .addComponent(insert)
                    .addComponent(volver))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        try {
            r.first();
            cod_art.setText(r.getString("cod_articulo"));
            arti.setText(r.getString("articulo"));
            fabri.setText(r.getString("fabricante"));
            peso.setText(r.getString("peso"));
            preciovent.setText(r.getString("precio_venta"));
            preciocost.setText(r.getString("precio_coste"));
            existenc.setText(r.getString("existencias"));
            category.setText(r.getString("categoria"));
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_firstActionPerformed

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        try {
            r.last();
            cod_art.setText(r.getString("cod_articulo"));
            arti.setText(r.getString("articulo"));
            fabri.setText(r.getString("fabricante"));
            peso.setText(r.getString("peso"));
            preciovent.setText(r.getString("precio_venta"));
            preciocost.setText(r.getString("precio_coste"));
            existenc.setText(r.getString("existencias"));
            category.setText(r.getString("categoria"));
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lastActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        try {
            if(r.next()){
                cod_art.setText(r.getString("cod_articulo"));
                arti.setText(r.getString("articulo"));
                fabri.setText(r.getString("fabricante"));
                peso.setText(r.getString("peso"));
                preciovent.setText(r.getString("precio_venta"));
                preciocost.setText(r.getString("precio_coste"));
                existenc.setText(r.getString("existencias"));
                category.setText(r.getString("categoria"));
            }
            
           } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
          
                
                // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        try {
            if(r.previous()){
                cod_art.setText(r.getString("cod_articulo"));
                arti.setText(r.getString("articulo"));
                fabri.setText(r.getString("fabricantes"));
                peso.setText(r.getString("peso"));
                preciovent.setText(r.getString("precio_venta"));
                preciocost.setText(r.getString("precio_coste"));
                existenc.setText(r.getString("existencias"));
                category.setText(r.getString("categoria"));
            }
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_previousActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try{
            String vCodArticulo, vArticulo, vFabricante, vPeso, vPrecioVenta, vPrecioCoste, vExistencias, vCategoria;
            vCodArticulo = cod_art.getText();
            vArticulo   = arti.getText();
            vFabricante = fabri.getText();
            vPeso = peso.getText();
            vPrecioVenta = preciovent.getText();        
            vPrecioCoste = preciocost.getText();
            vExistencias = existenc.getText();
            vCategoria = category.getText();
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url,user,pass);
            Statement s = connection.createStatement();
            String query = "update articulos set ARTICULO='" + vArticulo + "', FABRICANTE='" + vFabricante + "', PESO='" + vPeso + "', PRECIO_VENTA='" + vPrecioVenta + "', PRECIO_COSTE='" + vPrecioCoste + "', EXISTENCIAS='" + vExistencias + "', CATEGORIA='" + vCategoria + "'  WHERE COD_ARTICULO='" + vCodArticulo +"'";
            int resultado = s.executeUpdate(query);
            r.refreshRow();                     
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        




        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        first.setVisible(false);
        next.setVisible(false);
        previous.setVisible(false);
        last.setVisible(false);
        edit.setVisible(false);
        insert.setVisible(false);
        guardar.setVisible(true);
        cancelar.setVisible(true);
        cod_art.setEditable(true);
        arti.setText("");
        fabri.setText("");
        peso.setText("");
        preciovent.setText("");
        preciocost.setText("");
        existenc.setText("");
        category.setText("");






        // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            String vCod_articulo, vArticulo, vFabricante, vPeso, vPrecio_venta, vPrecio_coste, vExistencias, vCategoria;
            vCod_articulo = cod_art.getText();
            vArticulo = arti.getText();
            vFabricante = fabri.getText();
            vPeso = peso.getText();
            vPrecio_venta = preciovent.getText();
            vPrecio_coste = preciocost.getText();
            vExistencias = existenc.getText();
            vCategoria = category.getText();
            String url = "jdbc:mysql://localhost:3306/entornos";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement();
            String query = "insert into articulos values ('" +vCod_articulo + "','" +vArticulo + "','" + vFabricante + "','" + vPeso + "','" + vPrecio_venta + "','" + vPrecio_coste + "','" + vExistencias + "','" + vCategoria + "')";
            int resultado=s.executeUpdate(query);
            r.refreshRow();
            
            String query2 = "select * from articulos";
          r = s.executeQuery(query2);
          r.first();
                cod_art.setText(r.getString("COD_ARTICULO"));
                arti.setText(r.getString("ARTICULO"));
                fabri.setText(r.getString("FABRICANTE"));
                peso.setText(r.getString("PESO"));
                preciovent.setText(r.getString("PRECIO_VENTA"));
                preciocost.setText(r.getString("PRECIO_COSTE"));
                existenc.setText(r.getString("EXISTENCIAS"));
                category.setText(r.getString("CATEGORIA"));
                edit.setVisible(true);
                first.setVisible(true);
                previous.setVisible(true);
                next.setVisible(true);
                last.setVisible(true);
                insert.setVisible(true);
                guardar.setVisible(false);
                cancelar.setVisible(false);
                cod_art.setEditable(false);
                
                } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        edit.setVisible(true);
        first.setVisible(true);
        previous.setVisible(true);
        next.setVisible(true);
        last.setVisible(true);
        insert.setVisible(true);
        guardar.setVisible(false);
        cancelar.setVisible(false);
        cod_art.setEditable(false);
        
        try {
        r.first();
                cod_art.setText(r.getString("COD_ARTICULO"));
                arti.setText(r.getString("ARTICULO"));
                fabri.setText(r.getString("FABRICANTE"));
                peso.setText(r.getString("PESO"));
                preciovent.setText(r.getString("PRECIO_VENTA"));
                preciocost.setText(r.getString("PRECIO_COSTE"));
                existenc.setText(r.getString("EXISTENCIAS"));
                category.setText(r.getString("CATEGORIA"));
                
                } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        menu art= new menu();
        art.setLocationRelativeTo (null);
        this.setVisible(false);
        art.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arti;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField category;
    private javax.swing.JTextField cod_art;
    private javax.swing.JButton edit;
    private javax.swing.JTextField existenc;
    private javax.swing.JTextField fabri;
    private javax.swing.JButton first;
    private javax.swing.JButton guardar;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton last;
    private javax.swing.JButton next;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField preciocost;
    private javax.swing.JTextField preciovent;
    private javax.swing.JButton previous;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
